title: Hatzakis Lab
description: > # this means to ignore newlines until "author:"
  Single Molecule Microscopy Lab at the University of Copenhagen
author: Hatzakis Lab
keyword: jekyll
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hatzakislab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  "hatzakislab"

social:
  name: Nikos Hatzakis
  links:
    - https://twitter.com/nhatzakis
    - http://linkedin.com/in/nikoshatzakis
    - https://orcid.org/0000-0003-4202-0328

google_verify: google59e9fde1d35d1916.html

markdown: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - agency-jekyll-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
